### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by davidar** [lukasmartinelli/naturalearthtiles#1]
WebP is only supported by Chrome and Opera. The raster tiles fail to render in all other browsers.

http://caniuse.com/#feat=webp

**Comment by lukasmartinelli** [comment]
> WebP is only supported by Chrome and Opera. The raster tiles fail to render in all other browsers.

Uppps thanks. Didn't know that - okay that is sad so I have to create new MBTiles with *.png.

**Comment by lukasmartinelli** [comment]
I updated the files in GitHub pages so the maps http://naturalearthtiles.org/ and my style http://osm-liberty.lukasmartinelli.ch/ that depend on it now work in other browsers.

MBTiles I still need to convert (do you even want that or is CDN enough)?

**Comment by davidar** [comment]
CDN is enough for now. Thanks!

**Comment by kind3r** [comment]
Hi,

What's the easyest way to convert the raster WebP mbtiles to PNG mbtiles ?

Thanks
